# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
---

minimum_pre_commit_version: 1.16.1

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: pretty-format-json
        args: ['--autofix', '--indent=2', '--no-sort-keys']

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.16.0
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: shellcheck
      - id: shfmt
        args: ['-l', '-i', '4', '-ci', '-w']

  - repo: https://github.com/openstack-dev/bashate.git
    rev: '0.6.0'
    hooks:
      - id: bashate

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.17.0
    hooks:
      - id: markdownlint
