#!/usr/bin/env bash

###
# Print error into STDERR
###
error() {
    echo "$@" 1>&2
}

###
# Get latest release for a GitHub repository
###
get_latest_release() {
    local repository=$1
    local url="https://api.github.com/repos/${repository}/releases/latest"
    if [ ! -z "$GITHUB_OAUTH_TOKEN" ]; then
        url="${url}?access_token=${GITHUB_OAUTH_TOKEN}"
    fi
    curl --silent "${url}" | \
        grep '"tag_name":' | \
        sed -E 's/.*"([^"]+)".*/\1/'
}

###
# Get latest tag from a GitHub repository
###
get_latest_tag() {
    local repository=$1
    local url="https://api.github.com/repos/${repository}/tags?per_page=1"
    if [ ! -z "$GITHUB_OAUTH_TOKEN" ]; then
        url="${url}&access_token=${GITHUB_OAUTH_TOKEN}"
    fi
    curl --silent "${url}" | \
        grep '"name":' | \
        sed -E 's/.*"([^"]+)".*/\1/'
}


###
# Update asdf version
###
update_asdf_version() {
    local version=$1
    update_variable "asdf_version" ${version}
}

###
# Update Ansible variable
###
update_variable() {
    local key=$1
    local value=$2
    local file=defaults/main.yml
    sed -i.save -r "s/^($key):.*$/\1: \"${value}\"/" \
        ${file}
    rm ${file}.save
}

###
# Get latest asdf version
###
latest_asdf_version() {
    local latest_release=""
    local errmsg="Failed to get latest asdf-vm/asdf release"
    latest_release=$(get_latest_tag asdf-vm/asdf)
    [ -z "${latest_release}" ] && { error "${errmsg}"; return 1; }
    echo "${latest_release}"
}

###
# Update all versions
###
update_versions() {
    local repository=$1
    if [ -z "${repository}" ]; then
        error "Repository not defined"
        exit 1
    fi
    if [ "${repository}" == "asdf" ]; then
        ASDF_VERSION=$(latest_asdf_version)
        echo "Latest asdf release is ${ASDF_VERSION}"
        update_asdf_version ${ASDF_VERSION}
    else
        error "Unknown repository: ${repository}"
        exit 1
    fi
}

check_requirements() {
    command -v curl > /dev/null || { error "curl is not installed"; exit 1; }
}

set -e

check_requirements
update_versions $1
