---

- name: Load dependencies for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "deps.{{ ansible_distribution }}.yml"
      - "deps.{{ ansible_os_family }}.yml"
      skip: true

- name: Install dependencies with apt
  become: True
  apt:
    name: "{{ asdf_dependencies }}"
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install dependencies with Homebrew
  homebrew:
    name: "{{ asdf_dependencies }}"
  when: ansible_os_family == "Darwin"

- name: "Clone asdf repository"
  git:
    repo: "{{ asdf_git_repo }}"
    dest: "{{ asdf_dir }}"
    version: "{{ asdf_version }}"
