---
# tasks file for markosamuli.asdf

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true

- name: Install asdf version manager
  include_tasks: install.yml

- name: Initialise shell
  include_tasks: shell.yml
